import { createFileRoute } from "@tanstack/react-router";
import { useFarm } from "@/lib/farm-context";
import { AnimatedCounter } from "@/components/AnimatedCounter";
import {
  Droplets, FlaskConical, Bug, Sprout, Calendar, CloudSun, AlertTriangle, HelpCircle, Gauge,
} from "lucide-react";

export const Route = createFileRoute("/_app/ai-analysis")({
  head: () => ({ meta: [{ title: "AI Analysis · AgriTwin AI" }] }),
  component: AIAnalysis,
});

function RecommendationCard({ icon: Icon, title, body, tone = "primary" }: any) {
  const toneCls: Record<string, string> = {
    primary: "from-primary/25 to-primary-glow/10 text-primary",
    info: "from-info/25 to-info/5 text-info",
    warning: "from-warning/25 to-warning/5 text-warning",
    destructive: "from-destructive/25 to-destructive/5 text-destructive",
  };
  return (
    <div className="glass card-hover rounded-2xl p-6 relative overflow-hidden">
      <div className={`absolute -top-16 -right-16 h-40 w-40 rounded-full blur-3xl bg-gradient-to-br ${toneCls[tone]}`} />
      <div className="relative flex items-start gap-4">
        <div className={`h-11 w-11 rounded-xl grid place-items-center bg-gradient-to-br ${toneCls[tone]}`}>
          <Icon className="h-5 w-5" />
        </div>
        <div className="min-w-0">
          <h3 className="font-semibold">{title}</h3>
          <p className="mt-1 text-sm text-muted-foreground leading-relaxed">{body}</p>
        </div>
      </div>
    </div>
  );
}

function AIAnalysis() {
  const { scenario } = useFarm();

  const recs: Record<string, Record<string, string>> = {
    healthy: {
      water: "Maintain 2.4 L/plant daily. Skip Wednesday if forecast rain holds.",
      fert: "Apply light foliar potassium (0.5%) next week to support flowering.",
      disease: "No active disease. Continue weekly scouting rotation.",
      growth: "Growth tracking 6% above baseline. On schedule for early harvest.",
      harvest: "Predicted harvest window: 22–26 days.",
      weather: "Stable sunny conditions. Ideal solar radiation for photosynthesis.",
      risk: "Overall risk minimal.",
    },
    dry: {
      water: "Urgent: irrigate 4.5 L/plant in the west quadrant within 3 hours.",
      fert: "Delay fertilizer until moisture recovers to avoid root burn.",
      disease: "Elevated leaf-curl risk in zone C. Deploy scouting drone.",
      growth: "Growth stalled 12% due to drought stress. Recovery expected in 5 days.",
      harvest: "Predicted harvest window slipped by 6 days.",
      weather: "Hot & dry front for 48 hours. Consider shade netting for tender crops.",
      risk: "Water stress: HIGH. Yield impact projected -14%.",
    },
    disease: {
      water: "Reduce watering 20% to lower humidity in canopy.",
      fert: "Add potassium silicate to strengthen cell walls.",
      disease: "Fungal outbreak (Blight) in NE quadrant. Copper spray recommended tonight.",
      growth: "Growth suppressed by pathogen load; expect 8% delay.",
      harvest: "Predicted harvest window: 38–42 days if outbreak contained.",
      weather: "High humidity favors disease. Ventilate greenhouse if applicable.",
      risk: "Disease spread: CRITICAL. Immediate action required.",
    },
  };

  const r = recs[scenario.key];

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">AI Analysis</h1>
          <p className="text-muted-foreground text-sm mt-1">
            Generated by Fireworks AI · Llama 3 70B · Updated moments ago
          </p>
        </div>
      </div>

      <div className="glass rounded-3xl p-8 shadow-elegant relative overflow-hidden">
        <div className="absolute inset-0 -z-10 gradient-primary opacity-10" />
        <div className="flex flex-wrap items-center justify-between gap-6">
          <div>
            <div className="text-xs uppercase tracking-widest text-primary font-semibold">Overall Farm Health</div>
            <div className="mt-2 text-6xl font-bold text-gradient">
              <AnimatedCounter value={scenario.healthScore} />/100
            </div>
            <p className="mt-2 text-sm text-muted-foreground max-w-lg">{scenario.description}</p>
          </div>
          <div className="h-32 w-32 rounded-full grid place-items-center border-8 border-primary/30 relative">
            <Gauge className="h-10 w-10 text-primary" />
            <div className="absolute inset-0 rounded-full border-8 border-transparent border-t-primary animate-spin" style={{ animationDuration: "8s" }} />
          </div>
        </div>
      </div>

      <div className="grid md:grid-cols-2 gap-4">
        <RecommendationCard icon={Droplets} title="Water Recommendation" body={r.water} tone="info" />
        <RecommendationCard icon={FlaskConical} title="Fertilizer Recommendation" body={r.fert} tone="primary" />
        <RecommendationCard icon={Bug} title="Disease Analysis" body={r.disease} tone="destructive" />
        <RecommendationCard icon={Sprout} title="Growth Analysis" body={r.growth} tone="primary" />
        <RecommendationCard icon={Calendar} title="Harvest Prediction" body={r.harvest} tone="warning" />
        <RecommendationCard icon={CloudSun} title="Weather Impact" body={r.weather} tone="info" />
        <RecommendationCard icon={AlertTriangle} title="Risk Analysis" body={r.risk} tone={scenario.key === "healthy" ? "primary" : "destructive"} />
        <RecommendationCard
          icon={HelpCircle}
          title="Explain Why"
          body="Recommendations combine live sensor telemetry, 30-day weather forecast, plant physiology models and historical yield curves. Weighted by AMD-accelerated twin simulation."
        />
      </div>
    </div>
  );
}
