/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSensorNetworkRouteImport } from './routes/_app.sensor-network'
import { Route as AppPlantsRouteImport } from './routes/_app.plants'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppDigitalTwinRouteImport } from './routes/_app.digital-twin'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAiAnalysisRouteImport } from './routes/_app.ai-analysis'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSensorNetworkRoute = AppSensorNetworkRouteImport.update({
  id: '/sensor-network',
  path: '/sensor-network',
  getParentRoute: () => AppRoute,
} as any)
const AppPlantsRoute = AppPlantsRouteImport.update({
  id: '/plants',
  path: '/plants',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppDigitalTwinRoute = AppDigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAnalysisRoute = AppAiAnalysisRouteImport.update({
  id: '/ai-analysis',
  path: '/ai-analysis',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-analysis': typeof AppAiAnalysisRoute
  '/analytics': typeof AppAnalyticsRoute
  '/chat': typeof AppChatRoute
  '/digital-twin': typeof AppDigitalTwinRoute
  '/home': typeof AppHomeRoute
  '/plants': typeof AppPlantsRoute
  '/sensor-network': typeof AppSensorNetworkRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-analysis': typeof AppAiAnalysisRoute
  '/analytics': typeof AppAnalyticsRoute
  '/chat': typeof AppChatRoute
  '/digital-twin': typeof AppDigitalTwinRoute
  '/home': typeof AppHomeRoute
  '/plants': typeof AppPlantsRoute
  '/sensor-network': typeof AppSensorNetworkRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/ai-analysis': typeof AppAiAnalysisRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/digital-twin': typeof AppDigitalTwinRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/plants': typeof AppPlantsRoute
  '/_app/sensor-network': typeof AppSensorNetworkRoute
  '/_app/settings': typeof AppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-analysis'
    | '/analytics'
    | '/chat'
    | '/digital-twin'
    | '/home'
    | '/plants'
    | '/sensor-network'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-analysis'
    | '/analytics'
    | '/chat'
    | '/digital-twin'
    | '/home'
    | '/plants'
    | '/sensor-network'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/ai-analysis'
    | '/_app/analytics'
    | '/_app/chat'
    | '/_app/digital-twin'
    | '/_app/home'
    | '/_app/plants'
    | '/_app/sensor-network'
    | '/_app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sensor-network': {
      id: '/_app/sensor-network'
      path: '/sensor-network'
      fullPath: '/sensor-network'
      preLoaderRoute: typeof AppSensorNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plants': {
      id: '/_app/plants'
      path: '/plants'
      fullPath: '/plants'
      preLoaderRoute: typeof AppPlantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/digital-twin': {
      id: '/_app/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof AppDigitalTwinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-analysis': {
      id: '/_app/ai-analysis'
      path: '/ai-analysis'
      fullPath: '/ai-analysis'
      preLoaderRoute: typeof AppAiAnalysisRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiAnalysisRoute: typeof AppAiAnalysisRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppChatRoute: typeof AppChatRoute
  AppDigitalTwinRoute: typeof AppDigitalTwinRoute
  AppHomeRoute: typeof AppHomeRoute
  AppPlantsRoute: typeof AppPlantsRoute
  AppSensorNetworkRoute: typeof AppSensorNetworkRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiAnalysisRoute: AppAiAnalysisRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppChatRoute: AppChatRoute,
  AppDigitalTwinRoute: AppDigitalTwinRoute,
  AppHomeRoute: AppHomeRoute,
  AppPlantsRoute: AppPlantsRoute,
  AppSensorNetworkRoute: AppSensorNetworkRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
