/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppZonesRouteImport } from './routes/_app.zones'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSensorNetworkRouteImport } from './routes/_app.sensor-network'
import { Route as AppScanRouteImport } from './routes/_app.scan'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppPlantsRouteImport } from './routes/_app.plants'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppIrrigationRouteImport } from './routes/_app.irrigation'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppFertilizerRouteImport } from './routes/_app.fertilizer'
import { Route as AppDigitalTwinRouteImport } from './routes/_app.digital-twin'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppAiAnalysisRouteImport } from './routes/_app.ai-analysis'
import { Route as AppAboutRouteImport } from './routes/_app.about'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppZonesRoute = AppZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSensorNetworkRoute = AppSensorNetworkRouteImport.update({
  id: '/sensor-network',
  path: '/sensor-network',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPlantsRoute = AppPlantsRouteImport.update({
  id: '/plants',
  path: '/plants',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppIrrigationRoute = AppIrrigationRouteImport.update({
  id: '/irrigation',
  path: '/irrigation',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppFertilizerRoute = AppFertilizerRouteImport.update({
  id: '/fertilizer',
  path: '/fertilizer',
  getParentRoute: () => AppRoute,
} as any)
const AppDigitalTwinRoute = AppDigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAnalysisRoute = AppAiAnalysisRouteImport.update({
  id: '/ai-analysis',
  path: '/ai-analysis',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AppAboutRoute
  '/ai-analysis': typeof AppAiAnalysisRoute
  '/alerts': typeof AppAlertsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/chat': typeof AppChatRoute
  '/digital-twin': typeof AppDigitalTwinRoute
  '/fertilizer': typeof AppFertilizerRoute
  '/home': typeof AppHomeRoute
  '/irrigation': typeof AppIrrigationRoute
  '/notifications': typeof AppNotificationsRoute
  '/plants': typeof AppPlantsRoute
  '/reports': typeof AppReportsRoute
  '/scan': typeof AppScanRoute
  '/sensor-network': typeof AppSensorNetworkRoute
  '/settings': typeof AppSettingsRoute
  '/zones': typeof AppZonesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AppAboutRoute
  '/ai-analysis': typeof AppAiAnalysisRoute
  '/alerts': typeof AppAlertsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/chat': typeof AppChatRoute
  '/digital-twin': typeof AppDigitalTwinRoute
  '/fertilizer': typeof AppFertilizerRoute
  '/home': typeof AppHomeRoute
  '/irrigation': typeof AppIrrigationRoute
  '/notifications': typeof AppNotificationsRoute
  '/plants': typeof AppPlantsRoute
  '/reports': typeof AppReportsRoute
  '/scan': typeof AppScanRoute
  '/sensor-network': typeof AppSensorNetworkRoute
  '/settings': typeof AppSettingsRoute
  '/zones': typeof AppZonesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/_app/ai-analysis': typeof AppAiAnalysisRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/digital-twin': typeof AppDigitalTwinRoute
  '/_app/fertilizer': typeof AppFertilizerRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/irrigation': typeof AppIrrigationRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/plants': typeof AppPlantsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/scan': typeof AppScanRoute
  '/_app/sensor-network': typeof AppSensorNetworkRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/zones': typeof AppZonesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-analysis'
    | '/alerts'
    | '/analytics'
    | '/chat'
    | '/digital-twin'
    | '/fertilizer'
    | '/home'
    | '/irrigation'
    | '/notifications'
    | '/plants'
    | '/reports'
    | '/scan'
    | '/sensor-network'
    | '/settings'
    | '/zones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-analysis'
    | '/alerts'
    | '/analytics'
    | '/chat'
    | '/digital-twin'
    | '/fertilizer'
    | '/home'
    | '/irrigation'
    | '/notifications'
    | '/plants'
    | '/reports'
    | '/scan'
    | '/sensor-network'
    | '/settings'
    | '/zones'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/about'
    | '/_app/ai-analysis'
    | '/_app/alerts'
    | '/_app/analytics'
    | '/_app/chat'
    | '/_app/digital-twin'
    | '/_app/fertilizer'
    | '/_app/home'
    | '/_app/irrigation'
    | '/_app/notifications'
    | '/_app/plants'
    | '/_app/reports'
    | '/_app/scan'
    | '/_app/sensor-network'
    | '/_app/settings'
    | '/_app/zones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/zones': {
      id: '/_app/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof AppZonesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sensor-network': {
      id: '/_app/sensor-network'
      path: '/sensor-network'
      fullPath: '/sensor-network'
      preLoaderRoute: typeof AppSensorNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plants': {
      id: '/_app/plants'
      path: '/plants'
      fullPath: '/plants'
      preLoaderRoute: typeof AppPlantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/irrigation': {
      id: '/_app/irrigation'
      path: '/irrigation'
      fullPath: '/irrigation'
      preLoaderRoute: typeof AppIrrigationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fertilizer': {
      id: '/_app/fertilizer'
      path: '/fertilizer'
      fullPath: '/fertilizer'
      preLoaderRoute: typeof AppFertilizerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/digital-twin': {
      id: '/_app/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof AppDigitalTwinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-analysis': {
      id: '/_app/ai-analysis'
      path: '/ai-analysis'
      fullPath: '/ai-analysis'
      preLoaderRoute: typeof AppAiAnalysisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppAiAnalysisRoute: typeof AppAiAnalysisRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppChatRoute: typeof AppChatRoute
  AppDigitalTwinRoute: typeof AppDigitalTwinRoute
  AppFertilizerRoute: typeof AppFertilizerRoute
  AppHomeRoute: typeof AppHomeRoute
  AppIrrigationRoute: typeof AppIrrigationRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPlantsRoute: typeof AppPlantsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppScanRoute: typeof AppScanRoute
  AppSensorNetworkRoute: typeof AppSensorNetworkRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppZonesRoute: typeof AppZonesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppAiAnalysisRoute: AppAiAnalysisRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppChatRoute: AppChatRoute,
  AppDigitalTwinRoute: AppDigitalTwinRoute,
  AppFertilizerRoute: AppFertilizerRoute,
  AppHomeRoute: AppHomeRoute,
  AppIrrigationRoute: AppIrrigationRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPlantsRoute: AppPlantsRoute,
  AppReportsRoute: AppReportsRoute,
  AppScanRoute: AppScanRoute,
  AppSensorNetworkRoute: AppSensorNetworkRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppZonesRoute: AppZonesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
